# --- Etapa 1: Compilación ---
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
# Genera la distribución de producción
RUN npm run build

# --- Etapa 2: Servidor de Producción ---
FROM nginx:alpine

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar los estáticos compilados desde la etapa anterior
# Nota: Revisa la carpeta final que genera Angular dentro de dist/ (a veces incluye el nombre del proyecto)
COPY --from=build /app/dist/Frontend/browser /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]